# Generated by Django 6.0.4 on 2026-04-24 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('espece', models.CharField(max_length=50)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('age_estime', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='animaux/')),
                ('disponible_adoption', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En maintenance')], default='actif', max_length=20)),
                ('batterie', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperature_actuelle', models.FloatField(blank=True, null=True)),
                ('connectivite', models.CharField(blank=True, max_length=50)),
                ('temperature_cible', models.FloatField(blank=True, null=True)),
                ('piece', models.CharField(blank=True, max_length=100)),
                ('date_installation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_interaction', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets', to='core.categorieobjet')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
