# Generated by Django 6.0.4 on 2026-04-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateTimeField()),
                ('type_donnee', models.CharField(max_length=50)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapports.objetconnecte')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisationObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateTimeField()),
                ('duree_minutes', models.IntegerField()),
                ('consommation', models.FloatField()),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapports.objetconnecte')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapports.service')),
            ],
        ),
    ]
