# Generated by Django 6.0.4 on 2026-04-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisationobjet',
            name='objet',
        ),
        migrations.RemoveField(
            model_name='utilisationobjet',
            name='service',
        ),
        migrations.DeleteModel(
            name='HistoriqueDonnee',
        ),
        migrations.DeleteModel(
            name='ObjetConnecte',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='UtilisationObjet',
        ),
    ]
